import type { CreatorProfile } from "./types";

export const CREATOR_PROFILES: CreatorProfile[] = [
  {
    id: "creator-1",
    name: "Alex Rivera",
    email: "alex@creator.dev",
    niches: ["Fitness", "Lifestyle"],
    location: "US",
    platforms: ["TikTok", "Instagram"],
    followerRange: "10k+",
    bio: "Morning-run content and honest product reviews for active lifestyle brands.",
    stats: {
      totalFollowers: 14200,
      avgViews: 28400,
      avgEngagementRate: 6.8,
      completedCampaigns: 18,
      responseRate: 92,
      platforms: [
        { platform: "TikTok", followers: 9800, avgViews: 32000, engagementRate: 7.4 },
        { platform: "Instagram", followers: 4400, avgViews: 18500, engagementRate: 5.6 },
      ],
    },
    ugcPosts: [
      {
        id: "ugc-1",
        creatorId: "creator-1",
        title: "Summer run fit check",
        platform: "TikTok",
        campaignName: "Summer Running Campaign",
        brandName: "Nike",
        postedAt: "2026-07-02",
        views: 48200,
        likes: 3200,
        comments: 186,
        shares: 412,
        saves: 890,
      },
      {
        id: "ugc-2",
        creatorId: "creator-1",
        title: "5am training routine",
        platform: "Instagram",
        campaignName: "Summer Running Campaign",
        brandName: "Nike",
        postedAt: "2026-06-28",
        views: 22100,
        likes: 1840,
        comments: 94,
        shares: 88,
        saves: 310,
      },
    ],
  },
  {
    id: "creator-2",
    name: "Sam Chen",
    email: "sam@creator.dev",
    niches: ["Fashion", "Lifestyle"],
    location: "Los Angeles",
    platforms: ["Instagram"],
    followerRange: "5k+",
    bio: "Editorial-style reels and outfit transitions for fashion and boutique brands.",
    stats: {
      totalFollowers: 6800,
      avgViews: 12400,
      avgEngagementRate: 8.2,
      completedCampaigns: 11,
      responseRate: 88,
      platforms: [{ platform: "Instagram", followers: 6800, avgViews: 12400, engagementRate: 8.2 }],
    },
    ugcPosts: [
      {
        id: "ugc-3",
        creatorId: "creator-2",
        title: "Fall lookbook reel #1",
        platform: "Instagram",
        campaignName: "Fall Lookbook UGC",
        brandName: "Luna Boutique",
        postedAt: "2026-07-01",
        views: 15800,
        likes: 1420,
        comments: 67,
        shares: 45,
        saves: 520,
      },
    ],
  },
  {
    id: "creator-3",
    name: "Jordan Lee",
    email: "jordan.lee@creator.dev",
    niches: ["Fitness", "Sportswear"],
    location: "US",
    platforms: ["TikTok", "YouTube"],
    followerRange: "50k+",
    bio: "High-energy sportswear UGC with drill-style edits and gym-to-street transitions.",
    stats: {
      totalFollowers: 62400,
      avgViews: 89000,
      avgEngagementRate: 5.1,
      completedCampaigns: 34,
      responseRate: 95,
      platforms: [
        { platform: "TikTok", followers: 41000, avgViews: 112000, engagementRate: 5.8 },
        { platform: "YouTube", followers: 21400, avgViews: 48000, engagementRate: 3.9 },
      ],
    },
    ugcPosts: [
      {
        id: "ugc-4",
        creatorId: "creator-3",
        title: "Track day product test",
        platform: "TikTok",
        campaignName: "Summer Running Campaign",
        brandName: "Nike",
        postedAt: "2026-07-04",
        views: 124000,
        likes: 8900,
        comments: 420,
        shares: 1100,
        saves: 2400,
      },
      {
        id: "ugc-5",
        creatorId: "creator-3",
        title: "Full workout breakdown",
        platform: "YouTube",
        postedAt: "2026-06-20",
        views: 38000,
        likes: 2100,
        comments: 312,
        shares: 180,
        saves: 0,
      },
    ],
  },
  {
    id: "creator-4",
    name: "Priya Shah",
    email: "priya@glowtheory.com",
    niches: ["Beauty", "Skincare"],
    location: "Remote",
    platforms: ["TikTok", "Instagram"],
    followerRange: "8k+",
    bio: "Skincare routines, before/after framing, and tutorial-style serum launches.",
    stats: {
      totalFollowers: 9200,
      avgViews: 18600,
      avgEngagementRate: 9.4,
      completedCampaigns: 14,
      responseRate: 90,
      platforms: [
        { platform: "TikTok", followers: 5400, avgViews: 22000, engagementRate: 10.2 },
        { platform: "Instagram", followers: 3800, avgViews: 12800, engagementRate: 8.1 },
      ],
    },
    ugcPosts: [
      {
        id: "ugc-6",
        creatorId: "creator-4",
        title: "Vitamin C morning routine",
        platform: "TikTok",
        campaignName: "Serum Launch — Morning Routine",
        brandName: "Glow Theory",
        postedAt: "2026-07-03",
        views: 31200,
        likes: 2800,
        comments: 198,
        shares: 340,
        saves: 920,
      },
    ],
  },
  {
    id: "creator-5",
    name: "Maya Ortiz",
    email: "maya@lunaboutique.co",
    niches: ["Fashion"],
    location: "Los Angeles",
    platforms: ["Instagram"],
    followerRange: "3k+",
    bio: "Cozy boutique styling with warm tones and local LA brand partnerships.",
    stats: {
      totalFollowers: 3400,
      avgViews: 6200,
      avgEngagementRate: 11.2,
      completedCampaigns: 7,
      responseRate: 85,
      platforms: [{ platform: "Instagram", followers: 3400, avgViews: 6200, engagementRate: 11.2 }],
    },
    ugcPosts: [
      {
        id: "ugc-7",
        creatorId: "creator-5",
        title: "Transitional fall outfits",
        platform: "Instagram",
        campaignName: "Fall Lookbook UGC",
        brandName: "Luna Boutique",
        postedAt: "2026-06-30",
        views: 7800,
        likes: 890,
        comments: 42,
        shares: 28,
        saves: 410,
      },
    ],
  },
  {
    id: "creator-6",
    name: "Chris Nguyen",
    email: "chris@harborhearth.com",
    niches: ["Food", "Lifestyle"],
    location: "Seattle",
    platforms: ["TikTok"],
    followerRange: "2k+",
    bio: "Restaurant POV, recipe hooks, and cozy dining atmosphere content.",
    stats: {
      totalFollowers: 2800,
      avgViews: 9400,
      avgEngagementRate: 12.5,
      completedCampaigns: 5,
      responseRate: 80,
      platforms: [{ platform: "TikTok", followers: 2800, avgViews: 9400, engagementRate: 12.5 }],
    },
    ugcPosts: [
      {
        id: "ugc-8",
        creatorId: "creator-6",
        title: "Chef's table tasting reel",
        platform: "TikTok",
        brandName: "Harbor & Hearth",
        postedAt: "2026-07-05",
        views: 14200,
        likes: 1100,
        comments: 88,
        shares: 156,
        saves: 220,
      },
    ],
  },
];
