import type { MarketplaceData } from "./types";

export const SEED_MARKETPLACE_LISTINGS: MarketplaceData["listings"] = [
  {
    id: "mp-1",
    name: "Summer Running Campaign",
    brandName: "Nike",
    brandId: "brand-nike",
    campaignType: "experience",
    type: "mixed_bundle",
    exampleVideoLinks: [],
    status: "open",
    startDate: "2026-07-15",
    endDate: "2026-08-30",
    applicationDeadline: "2026-07-20",
    brief:
      "We're looking for authentic running content featuring our latest summer line. Creators should showcase real training routines, morning runs, and product integration in a natural lifestyle setting.",
    deliverables: "3 TikToks, 2 Instagram Reels, raw footage",
    requirements: ["US-based", "10k+ followers on at least one platform", "Previous sportswear UGC"],
    files: [
      { id: "f1", name: "creative-brief.pdf", sizeLabel: "1.2 MB" },
      { id: "f2", name: "brand-guidelines.pdf", sizeLabel: "890 KB" },
      { id: "f3", name: "product-lookbook.zip", sizeLabel: "14 MB" },
    ],
    payment: {
      structure: "milestone",
      currency: "USD",
      milestones: [
        { label: "Concept approval", amountCents: 75000, trigger: "Approved concept deck" },
        { label: "First draft", amountCents: 150000, trigger: "Draft videos delivered" },
        { label: "Final delivery", amountCents: 225000, trigger: "Final assets approved" },
      ],
      notes: "Net 30 after each milestone sign-off.",
    },
    location: "United States",
    remoteOk: true,
    slots: 5,
    applicantsCount: 12,
    postedAt: "2026-07-01T10:00:00.000Z",
  },
  {
    id: "mp-2",
    name: "Fall Lookbook UGC",
    brandName: "Luna Boutique",
    brandId: "brand-boutique",
    campaignType: "experience",
    type: "instagram_reels",
    exampleVideoLinks: [],
    status: "closing_soon",
    startDate: "2026-07-10",
    endDate: "2026-09-01",
    applicationDeadline: "2026-07-12",
    brief:
      "Local boutique seeking creators for a cozy fall lookbook. Focus on transitional outfits, boutique styling, and warm aesthetic tones.",
    deliverables: "4 Reels, 8 photos, 1 styling guide carousel",
    requirements: ["Fashion niche", "Female-identifying creators preferred", "LA area a plus"],
    files: [
      { id: "f4", name: "fall-lookbook-brief.pdf", sizeLabel: "640 KB" },
      { id: "f5", name: "mood-board.png", sizeLabel: "2.1 MB" },
    ],
    payment: {
      structure: "flat_rate",
      currency: "USD",
      flatAmountCents: 180000,
      notes: "50% upfront, 50% on delivery.",
    },
    location: "Los Angeles, CA",
    remoteOk: false,
    slots: 3,
    applicantsCount: 8,
    postedAt: "2026-06-28T10:00:00.000Z",
  },
  {
    id: "mp-3",
    name: "Serum Launch — Morning Routine",
    brandName: "Glow Theory",
    brandId: "brand-skincare",
    campaignType: "experience",
    type: "tiktok",
    exampleVideoLinks: [],
    status: "open",
    startDate: "2026-07-20",
    endDate: "2026-08-15",
    applicationDeadline: "2026-07-25",
    brief:
      "Launch campaign for our vitamin C serum. We want tutorial-style morning routine content with before/after framing and honest first impressions.",
    deliverables: "2 TikToks, 1 Instagram Reel",
    requirements: ["Beauty/skincare content", "Good lighting setup", "Disclosure-compliant"],
    files: [{ id: "f6", name: "serum-launch-kit.pdf", sizeLabel: "980 KB" }],
    payment: {
      structure: "flat_rate",
      currency: "USD",
      flatAmountCents: 220000,
    },
    location: "Remote",
    remoteOk: true,
    slots: 4,
    applicantsCount: 6,
    postedAt: "2026-07-03T10:00:00.000Z",
  },
  {
    id: "mp-4",
    name: "Creator Store Promo Q3",
    brandName: "ClothME",
    brandId: "brand-clothme",
    campaignType: "experience",
    type: "mixed_bundle",
    exampleVideoLinks: [],
    status: "open",
    startDate: "2026-07-01",
    endDate: "2026-07-31",
    applicationDeadline: "2026-07-15",
    brief:
      "Promote the ClothME creator store with authentic try-on and styling content. Highlight how creators monetize their looks.",
    deliverables: "2 TikToks, 1 Reel, 3 product photos",
    requirements: ["ClothME creator community member", "Fashion UGC experience"],
    files: [
      { id: "f7", name: "store-promo-brief.pdf", sizeLabel: "720 KB" },
      { id: "f8", name: "asset-pack.zip", sizeLabel: "22 MB" },
    ],
    payment: {
      structure: "hybrid",
      currency: "USD",
      hybridFlatCents: 200000,
      hybridRoyaltyPercent: 5,
      notes: "5% of attributed store sales for 60 days post-launch.",
    },
    location: "Remote",
    remoteOk: true,
    slots: 10,
    applicantsCount: 4,
    postedAt: "2026-06-25T10:00:00.000Z",
  },
  {
    id: "mp-5",
    name: "Summer Menu Launch Videos",
    brandName: "Harbor & Hearth",
    brandId: "brand-restaurant",
    campaignType: "experience",
    type: "tiktok",
    exampleVideoLinks: [],
    status: "open",
    startDate: "2026-08-01",
    endDate: "2026-08-31",
    applicationDeadline: "2026-07-28",
    brief:
      "Restaurant launching a new summer menu. Need short-form videos showcasing dishes, ambiance, and local foodie appeal.",
    deliverables: "3 TikToks, 1 hero Reel",
    requirements: ["Food/lifestyle creators", "Seattle area preferred", "On-site shoot required"],
    files: [{ id: "f9", name: "menu-launch-overview.pdf", sizeLabel: "540 KB" }],
    payment: {
      structure: "flat_rate",
      currency: "USD",
      flatAmountCents: 120000,
      notes: "Includes meal comp on shoot day.",
    },
    location: "Seattle, WA",
    remoteOk: false,
    slots: 2,
    applicantsCount: 3,
    postedAt: "2026-07-05T10:00:00.000Z",
  },
  {
    id: "mp-6",
    name: "Affiliate Wellness Series",
    brandName: "Vitality Co",
    campaignType: "experience",
    type: "youtube_shorts",
    exampleVideoLinks: [],
    status: "open",
    startDate: "2026-08-01",
    endDate: "2026-10-31",
    applicationDeadline: "2026-08-15",
    brief:
      "Ongoing affiliate partnership for wellness supplements. Creators produce monthly Shorts with custom codes and performance tracking.",
    deliverables: "2 Shorts per month for 3 months",
    requirements: ["Health/wellness niche", "Affiliate experience", "18+ audience"],
    files: [
      { id: "f10", name: "affiliate-terms.pdf", sizeLabel: "310 KB" },
      { id: "f11", name: "product-catalog.pdf", sizeLabel: "1.8 MB" },
    ],
    payment: {
      structure: "royalty",
      currency: "USD",
      royaltyPercent: 15,
      royaltyMinimumCents: 50000,
      notes: "15% commission per sale; $500/month minimum guarantee after month 1.",
    },
    location: "Remote",
    remoteOk: true,
    slots: 8,
    applicantsCount: 15,
    postedAt: "2026-07-06T10:00:00.000Z",
  },
];

export const SEED_MARKETPLACE_DATA: MarketplaceData = {
  customListings: [],
  listings: SEED_MARKETPLACE_LISTINGS,
  applications: [],
  crmLinkedListingIds: [],
};
