import type { BrandBillingData } from "./brand-billing-types";

export const SEED_BRAND_BILLING_DATA: BrandBillingData = {
  billing: {
    planName: "Brand Pro",
    planPriceCents: 14900,
    billingCycle: "monthly",
    billingEmail: "billing@clothme.io",
    companyName: "ClothME Inc.",
    addressLine1: "1200 Market Street",
    addressLine2: "Suite 400",
    city: "San Francisco",
    state: "CA",
    postalCode: "94103",
    country: "United States",
    nextInvoiceDate: "2026-08-01",
    taxId: "XX-XXXXXXX",
  },
  paymentMethods: [
    {
      id: "pm-1",
      label: "Visa",
      last4: "4242",
      expMonth: 8,
      expYear: 2028,
      isDefault: true,
    },
    {
      id: "pm-2",
      label: "Mastercard",
      last4: "8210",
      expMonth: 3,
      expYear: 2027,
      isDefault: false,
    },
  ],
  paymentHistory: [
    {
      id: "pay-1",
      date: "2026-07-01",
      description: "Brand Pro — July 2026",
      amountCents: 14900,
      status: "paid",
      invoiceNumber: "INV-2026-0701",
    },
    {
      id: "pay-2",
      date: "2026-06-01",
      description: "Brand Pro — June 2026",
      amountCents: 14900,
      status: "paid",
      invoiceNumber: "INV-2026-0601",
    },
    {
      id: "pay-3",
      date: "2026-05-01",
      description: "Brand Pro — May 2026",
      amountCents: 14900,
      status: "paid",
      invoiceNumber: "INV-2026-0501",
    },
    {
      id: "pay-4",
      date: "2026-04-15",
      description: "Creator payout batch — Q1 campaigns",
      amountCents: 425000,
      status: "paid",
      invoiceNumber: "INV-2026-0415",
    },
    {
      id: "pay-5",
      date: "2026-04-01",
      description: "Brand Pro — April 2026",
      amountCents: 14900,
      status: "paid",
      invoiceNumber: "INV-2026-0401",
    },
  ],
};
